send_order_url = 'http://dma-rest-res10-svia.cloudfinanza-svil.intesasanpaolo.com/U0I7391/fastfill/orders/createSimple';
send_options = weboptions('RequestMethod','post', 'MediaType','application/json','Timeout',60);

Instrument = struct('symbol','I', ...
    'securityExchange', 'ICE-LIFFE', ...
    'securityType', 'FUT', ...
    'maturityMonthYear', '202612');

Parties = struct( ...
    'account','BT', ...
    'executor','U392334', ...
    'investor','U392334');

orderId = num2str(now);

Order = struct( ...
	'timeInForce', 'IC'
    'secretKey','xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', ...
    'orderId',orderId, ...
    'qty', 5, ...
    'ordType','LIMIT', ...
    'side','SELL', ...
    'price',99, ...
    "senderLocationId","IT", ...
    'instrument', Instrument, ...
    'parties', Parties);

new_single_order = webwrite(send_order_url, Order);

% status_request_url = 'http://dma-rest-res10-svia.cloudfinanza-svil.intesasanpaolo.com/U0I7391/fastfill/history/738197.5125';
% status_options = weboptions('RequestMethod','get', 'MediaType','application/json','Timeout',60);
% status = webread(status_request_url,status_options);

